<?php

/**
 * @file
 * Contains ngt_process_images.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ngt_process_images_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the ngt module.
        case 'help.page.ngt_process_images':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('ngt process images') . '</p>';
        return $output;

    default:
    }
}



/**
 * Implements hook_theme().
 */
function ngt_process_images_theme() {
    return [
      'ngt_process_images_block' => [
        'variables' => [
          'data' => NULL,
          'directive'  => NULL,
          'uuid' => NULL,
          'config' => NULL,
          'class' => NULL,
          'plugin_id' => NULL,
          'form' => NULL,
        ],
        'template' => 'block--upload-images',
      ],
    ];
  }
  
  

